# Generated by Django 5.0.3 on 2024-06-17 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warhammer_api', '0002_alter_battle_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battle',
            name='factions',
        ),
    ]
