# Generated by Django 5.0.3 on 2024-06-17 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warhammer_api', '0003_remove_battle_factions'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='battlefaction',
            unique_together={('battle', 'faction')},
        ),
    ]
